version: 2.1

orbs:
  moul: moul/build@1.16.0 # https://github.com/moul/build

workflows:
  main:
    jobs:
      - moul/golang-build:
          gopkg: moul.io/bot
      - moul/golang-build:
          gopkg: moul.io/bot
          tag: '1.13'
      - moul/golang-build:
          gopkg: moul.io/bot
          tag: '1.12'
      - moul/golang-build:
          gopkg: moul.io/bot
          tag: '1.11'
      - moul/docker-build
